Feat: regradeExam 구현
swm-standard/Phote_BE pull request #246
Opened 2024-10-06 08:56 UTC by RinRinPARK

## **PR**

### ✨ 작업 내용

- regradeExam 구현했씁니당
- 별로 쓸게 없네요.. 일반적인 CRUD.. ㅎ..

---

### ✨ 참고 사항

---

### ⏰ 현재 버그

---

### ✏ Git Close #234

2024-10-06 10:04 UTC, adorableco requested changes
굿굿 다 잘 돌아가넨요~~~ 코드에 달아둔 코멘트만 한번 봐주시요

2024-10-06 10:04 UTC, adorableco commented on src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
> +        @PathVariable(required = true) userId: UUID,
```suggestion
        @PathVariable(required = true) memberId: UUID,
```
저희 `userId` -> `memberId` 로 통일 어떠신가요 ~~~~ auth 쪽은 나중에 내가 바꿔놓을게

2024-10-06 10:04 UTC, adorableco commented on src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
> +    @PostMapping("/exam/{examId}/{userId}")
```suggestion
    @PatchMapping("/exam/{examId}/{userId}")
```
patch 어떤가유

2024-10-06 14:33 UTC, RinRinPARK commented on src/main/kotlin/com/swm_standard/phote/controller/ExamController.kt
> +    @PostMapping("/exam/{examId}/{userId}")
그게맞지 그게맞ㅈㅣ POST이러고 잇엇네..

2024-10-07 02:51 UTC, adorableco approved these changes
아주아주 좋아요 ~ ~

2024-10-07 05:39 UTC, merged