Feat: deleteQuestionInWorkbook
swm-standard/Phote_BE pull request #68
Opened 2024-07-13 02:11 UTC by adorableco

## **PR**

### ✨ 작업 내용

- 문제집 내에서 문제 삭제 기능을 구현함

&nbsp;

**🙌🏻 응답 결과 🙌🏻**

**<성공>**

<img width="400" alt="스크린샷 2024-07-13 오전 10 57 31" src="https://github.com/user-attachments/assets/228ab551-b507-4c25-8564-4088ecb6c322">

&nbsp;
**<실패>**

<img width="400" alt="스크린샷 2024-07-13 오전 11 07 53" src="https://github.com/user-attachments/assets/4239ae79-7ba9-4f0b-b63f-1d8514202bf5">

---

### ✨ 참고 사항

- 해당 기능에서 쿼리문을 4번이나 호출하는데 아래 두개는 없애도 괜찮을까 고민이에요 기능 구현 상엔 없어도 문제가 없으나 단순 exception 처리용인 느낌..

```Kotlin
     workbookRepository.findById(workbookId)
            .orElseThrow { NotFoundException(fieldName = "workbook", message = "id 를 재확인해주세요.") }

        questionRepository.findById(questionId)
            .orElseThrow { NotFoundException(fieldName = "question", message = "id 를 재확인해주세요.") }
```

---

### ⏰ 현재 버그

x

---

### ✏ Git Close #39

2024-07-13 02:54 UTC, RinRinPARK requested changes
``` 해당 기능에서 쿼리문을 4번이나 호출하는데 아래 두개는 없애도 괜찮을까 고민이에요 기능 구현 상엔 없어도 문제가 없으나 단순 exception 처리용인 느낌.. ```
--> 저도 동의 그냥 없애도 될 듯용~ 없애니까 그냥 문제집에 없는 문제다라고만 하던데 쬠 그렇긴 해도.. 맞는 말이니까!ㅋ.ㅋ 쿼리 여러번 부르는 것보단 나은 듯

2024-07-13 02:54 UTC, RinRinPARK commented on src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
> +    }
문제 삭제하고 나서 workbook에서 quantity속성 값도 -1 해줘야 할 것 같습니다!!
addQuestionToWorkbook api에서도 quantity 값을 하나 +1 해주는 걸로!

2024-07-13 15:07 UTC, adorableco commented on src/main/kotlin/com/swm_standard/phote/service/WorkbookService.kt
> +    }
너 완전 잘 발견한다....

방금 반영해놨으니 시간날 때 리뷰 부탁해~ ~ 참고로 문제 추가 시에는 여러 문제 추가가 가능해서 개수만큼 quantity가 증가되도록 했습니당

2024-07-13 15:11 UTC, adorableco commented
> `해당 기능에서 쿼리문을 4번이나 호출하는데 아래 두개는 없애도 괜찮을까 고민이에요 기능 구현 상엔 없어도 문제가 없으나 단순 exception 처리용인 느낌..` --> 저도 동의 그냥 없애도 될 듯용~ 없애니까 그냥 문제집에 없는 문제다라고만 하던데 쬠 그렇긴 해도.. 맞는 말이니까!ㅋ.ㅋ 쿼리 여러번 부르는 것보단 나은 듯

코멘트 반영하면서 questionRepository 호출 부분은 삭제했구 workbookRepository 부분은 quantity 변경 시에 필요해서 그대로 뒀습니당

2024-07-14 02:29 UTC, RinRinPARK approved these changes
구웃!! 확인했으용

2024-07-14 02:52 UTC, merged